server:
  port: 6060
  servlet:
    context-path: /note-api

spring:
  application:
    name: note
  profiles:
    active: dev
  flyway:
    enabled: true
  main:
    allow-bean-definition-overriding: true

soul:
  ability:
    security:
      jwt:
        claims:
          exp: 604800  # 7 days
      spring:
        jwt:
          enable: true
        session:
#          type: header
          header:
            name: SID

  ms:
    fserver:
      api:
        view:
          list-enable: false
          location: ${fserver.root.location}
          public-endpoint: ${fserver.root.public-endpoint}

# Print the SQL
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  group-configs:
    - group: node
      display-name: node book doc
      packages-to-scan: org.open.lang.ms.note.api.module


logging:
  # 指定日志配置环境
  config: classpath:logback-spring.xml
  level:
    root: INFO

management:
  health:
    redis:
      enabled: false
