server:
  port: 8080
  servlet:
    context-path: /note-api

spring:
  application:
    name: note
  profiles:
    active: dev
soul:
  ability:
    security:
      jwt:
        claims:
          exp: 604800  # 7 days
      spring:
        jwt:
          enable: true

  ms:
    fserver:
      api:
        view:
          list-enable: false
          location: ${fserver.root.location}
          public-endpoint: ${fserver.root.public-endpoint}

# Print the SQL
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
